# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/giulia/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),giulia)

$(call add-radio-file-sha1-checked,radio/abl.img,2018b851e884aabbd00f420052caada94549e341)
$(call add-radio-file-sha1-checked,radio/aop.img,e0ae1377d532b614f687cd73aa9aa385cf401582)
$(call add-radio-file-sha1-checked,radio/aop_config.img,80d29350cdb21b38869e83219c7e9dc983e97273)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,9c0099e054607388045a2148ddb14967ab239370)
$(call add-radio-file-sha1-checked,radio/cpucp.img,f57034bb1ba49caef2e1aa1fcb0037fa98d9ff50)
$(call add-radio-file-sha1-checked,radio/cpucp_dtb.img,28790c94982b1ab751cb4c965200758cebd07d8f)
$(call add-radio-file-sha1-checked,radio/devcfg.img,250ad7856a83599861baa704719ad86cf9d3b9e7)
$(call add-radio-file-sha1-checked,radio/dsp.img,72075bb397712d2b7753e2a8654cf8e5c2313602)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,99e44bb313d949f1ee2eabb2add72256b4bc5e36)
$(call add-radio-file-sha1-checked,radio/featenabler.img,5c23105c9a3d1892f0387063211c837a94fd2c6c)
$(call add-radio-file-sha1-checked,radio/hyp.img,ac95140abaa4a1b222128a73485d21cdd36d2a64)
$(call add-radio-file-sha1-checked,radio/imagefv.img,fef9eea272677cc5bf74def26263851414eb9e86)
$(call add-radio-file-sha1-checked,radio/keymaster.img,f867d0d6ae8facc89388fb3ee0100a1ed3a234d9)
$(call add-radio-file-sha1-checked,radio/modem.img,25f8b471bd6c6b34ea428d64e939b82a48f2a6a2)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,2a0a3bc41fa77874e80515aaee0a151fd7ea2756)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,3f48a2ae596a0ae7f062ecd7b78886a1502bdcfa)
$(call add-radio-file-sha1-checked,radio/qupfw.img,d218250b46428e1a639923c0c6eb4f8e9c0dd8cc)
$(call add-radio-file-sha1-checked,radio/shrm.img,b252be98e6219ba7f9d178092e3099312a5719e5)
$(call add-radio-file-sha1-checked,radio/splash.img,07e9cda27d7d55806370294443d78ef887e32d2b)
$(call add-radio-file-sha1-checked,radio/tz.img,77447c504a5fd7cb13e7a0171af4ba7f748f477d)
$(call add-radio-file-sha1-checked,radio/uefi.img,10aa1a5f25c7b9b7542376ac881fdb4fa3826920)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,6d4eda448d6ab953f28818df417476b7a8dc063a)
$(call add-radio-file-sha1-checked,radio/xbl.img,2733341db84b5f2f1ca19a394524718516fa37bb)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,ab22271ce3f9577e2a56c4fdd863721b6484a237)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,e83b6eb769060f2907420415b57a26bd13ae4d43)

endif
